# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [2chainz, PBS]
patreon: # Replace with a single Patreon username kingjames
open_collective: # Replace with a single Open Collective username metamask.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username alpa35
issuehunt: # Replace with a single IssueHunt username masterkey 
otechie: # Replace with a single Otechie username Russian87
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://mad.org/','https://TikTok.com','https://nytimes.com','https://www.ae911truth.org/fbi','https://pornhub.com','https://Wikileaks.com','https://homedepot.com','https://pbs.org','https://fuckcancer.org']
